modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121/EnchantingWithTFC/issues"

[[mods]]
modId="enchanting_with_tfc"
version="1.0.0"
displayName="EnchantingWithTFC"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enchanting_with_tfc"
authors="Mrthomas20121"
description='''
Enable enchanting table and add new specific tfc enchantment.
'''

[[dependencies.enchanting_with_tfc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"